/**
 * Mappings and Dictionaries for Data Cleaning
 * Migrated from Pipeline/main.py
 */

// 1. Map of Server Names (Padronização de Servidores)
export const SERVER_NAME_MAP = {
    "Camila do Lago Marins": "Camila Marins",
    "Camila Marins": "Camila Marins",
    "Dhayane Cristina Pinho de Almeida": "Dhayane Cristina Pinho de Almeida",
    "Dhayane Pinho": "Dhayane Cristina Pinho de Almeida",
    "Joana Darc Salles Ferreira": "Joana Darc Salles Ferreira",
    "Joana Salles": "Joana Darc Salles Ferreira",
    "Lucia Helena Tinoco Pacehco Varella": "Lúcia Helena Tinoco Pacheco Varella",
    "Lucia Helena Tinoco Pacheco Varella": "Lúcia Helena Tinoco Pacheco Varella",
    "Lucia  Helena Tinoco Pacheco Varella": "Lúcia Helena Tinoco Pacheco Varella",
    "Lúcia  Helena Tinoco Pacheco Varella": "Lúcia Helena Tinoco Pacheco Varella",
    "Lúcia Helena Tinoco Pacheco Varella": "Lúcia Helena Tinoco Pacheco Varella",
    "Lucia Helenba Tinoco Pacheco Varella": "Lúcia Helena Tinoco Pacheco Varella",
    "Lucia Helana Tinoco Pacheco Varella": "Lúcia Helena Tinoco Pacheco Varella",
    "Rafaella Marques Gomes Santos": "Rafaella Marques Gomes Santos",
    "Roilene Pereira da Silva": "Rosilene Pereira da Silva",
    "Rosilene Pereira da Silva": "Rosilene Pereira da Silva",
    "Stephanie dos Santos Silva": "Stephanie dos Santos Silva",
    "Stephanie Santos": "Stephanie dos Santos Silva",
    "Stéphanie Santos": "Stephanie dos Santos Silva",
    "Stéphaniesantos": "Stephanie dos Santos Silva",
    "Stpehanie Santos": "Stephanie dos Santos Silva",
    "Anne Beatriz da Silva": "Anne Beatriz da Silva Rodrigues",
    "Bruna Maria ( Coordenadora)": "Cidadão",
    "Isabel": "Cidadão",
    "Gabriela da Silva Rozi": "Cidadão",
    "Lana Carolina Mesquita de Andrade": "Cidadão",
    "Lívia Cavalcante": "Lívia Kathleen Cavalcante Patriota Leite",
    "Lívia Kathleen Cavalcante Patriota Leite": "Lívia Kathleen Cavalcante Patriota Leite",
    "Lucia Helena": "Lúcia Helena Tinoco Pacheco Varella",
    "Lucia Helena Tin": "Lúcia Helena Tinoco Pacheco Varella",
    "Lucia Helena Tinoco": "Lúcia Helena Tinoco Pacheco Varella",
    "Lucia Helena Tinoco Varella": "Lúcia Helena Tinoco Pacheco Varella",
    "Lucia Helen Tinoco Varella": "Lúcia Helena Tinoco Pacheco Varella",
    "Lucia Helan Tinoco Pacheco Varella": "Lúcia Helena Tinoco Pacheco Varella",
    "Lucia Helena  Tinoco Pacheco Varella": "Lúcia Helena Tinoco Pacheco Varella",
    "Lucia Helena Tinoco Pachewco Varella": "Lúcia Helena Tinoco Pacheco Varella",
    "Talita Mrques Ferrari": "Talita Marques Ferrari",
    "Talita  Marques Ferrari": "Talita Marques Ferrari",
    "Mery": "Cidadão",
    "Ouvidoria Geral (Adm)": "Cidadão",
    "Rafaella Marques": "Rafaella Marques Gomes Santos",
    "Ronaldo de Oliveira Brandão": "Cidadão",
    "Séphanie Santos": "Stephanie dos Santos Silva",
    "Shirley Santana": "Cidadão",
    "Stépanie Santos": "Stephanie dos Santos Silva",
    "Stéphanie  Santos": "Stephanie dos Santos Silva",
    "Stephanie dos Santos": "Stephanie dos Santos Silva",
    "Stéphanie Santoa": "Stephanie dos Santos Silva",
    "Stephanie Santos": "Stephanie dos Santos Silva",
    "Thamires Manhães": "Cidadão",
    "Alexsandra de Castro Freire": "Cidadão"
};

// 2. Map of Themes to Secretariats (Órgãos)
export const THEME_TO_SECRETARIAT_MAP = {
    "Administração Pública": "Secretaria de Administração",
    "Agricultura": "Secretaria de Obras e Agricultura",
    "Assistência Social e Direitos Humanos": "Secretaria de Assistência Social e Direitos Humanos",
    "Assuntos Jurídicos": "Procuradoria Geral",
    "Comunicação Social": "Secretaria de Comunicação Social, Relações Públicas, Trabalho, Emprego e Renda",
    "Controle Governamental": "Secretaria de Controle Interno",
    "Criança, Adolescente e Idoso": "Secretaria de Assistência Social e Direitos Humanos",
    "Cultura e Turismo": "Secretaria de Cultura e Turismo",
    "Defesa Civil": "Secretaria de Defesa Civil",
    "Direitos à Pessoa com Deficiência": "Secretaria de Assistência Social e Direitos Humanos",
    "Direitos e Vantagens do Servidor": "Secretaria de Administração",
    "Educação": "Secretaria de Educação",
    "Empresas e Legalizações": "Secretaria de Fazenda",
    "Esporte e Lazer": "Secretaria de Esporte e Lazer",
    "Fiscalização e tributos": "Secretaria de Fazenda",
    "Fiscalização Urbana, Regularização e Registro de Imóveis": "Secretaria de Urbanismo e Habitação",
    "FUNDEC": "FUNDEC",
    "Governança": "Secretaria de Governo",
    "Governo Municipal e Enterro Gratuito": "Secretaria de Governo",
    "Habitação": "Secretaria de Urbanismo e Habitação",
    "Inclusão e Acessibilidade": "Secretaria de Gestão, Inclusão e Mulher",
    "Meio Ambiente": "Secretaria de Meio Ambiente",
    "Meio Ambiente (Poluição Sonora, Árvores, Licenças e Fiscalizações Ambientais e etc.)": "Secretaria de Meio Ambiente",
    "Assédio": "Secretaria de Comunicação Social, Relações Públicas, Trabalho, Emprego e Renda",
    "Obras Públicas": "Secretaria de Obras e Agricultura",
    "Obras, Limpeza Urbana e Braço de Luz": "Secretaria de Obras e Agricultura",
    "Proteção Animal": "Secretaria de Proteção Animal",
    "Saúde": "Secretaria de Saúde",
    "Segurança Pública": "Secretaria de Segurança Pública",
    "Segurança, Sinalização e Multas": "Secretaria de Segurança Pública",
    "Trabalho, Emprego e Renda": "Secretaria de Trabalho, Emprego e Renda",
    "Transportes e Serviços Públicos": "Secretaria de Transportes e Serviços Públicos",
    "Transportes, Serviços Públicos e Troca de Lâmpadas": "Secretaria de Transportes e Serviços Públicos",
    "Urbanismo": "Secretaria de Urbanismo e Habitação",
    "Vetores e Zoonoses (Combate à Dengue, Controle de Pragas, Criação Irregular de Animais e etc.)": "Secretaria de Saúde",
    "Vigilância Sanitária": "Secretaria de Saúde",
    "Obras": "Secretaria de Obras e Agricultura",
    "Trabalho": "Secretaria de Trabalho, Emprego e Renda",
    "Segurança": "Secretaria de Segurança Pública",
    "Serviços Públicos e Troca de Lâmpadas": "Secretaria de Transportes e Serviços Públicos",
    "Árvores": "Secretaria de Meio Ambiente",
    "Controle de Pragas": "Secretaria de Saúde",
    "Criação Irregular de Animais": "Secretaria de Saúde",
    "Adolescente e Idoso": "Secretaria de Assistência Social e Direitos Humanos",
    "Criança": "Secretaria de Assistência Social e Direitos Humanos",
    "Emprego e Renda": "Secretaria de Trabalho, Emprego e Renda",
    "Fiscalização Urbana": "Secretaria de Urbanismo e Habitação",
    "Regularização e Registro de Imóveis": "Secretaria de Urbanismo e Habitação",
    "Limpeza Urbana e Braço de Luz": "Secretaria de Obras e Agricultura",
    "Meio Ambiente (Poluição Sonora)": "Secretaria de Meio Ambiente",
    "Licenças e Fiscalizações Ambientais e etc.": "Secretaria de Meio Ambiente",
    "Vetores e Zoonoses (Combate à Dengue)": "Secretaria de Saúde",
    "Sinalização e Multas": "Secretaria de Segurança Pública",
    "Transportes": "Secretaria de Transportes e Serviços Públicos"
};

// 3. Map of Themes to Responsible Ombudsman (Ouvidoria Responsável)
export const THEME_TO_OMBUDSMAN_MAP = {
    "administração pública": "Ouvidoria Geral",
    "agricultura": "Ouvidoria Setorial de Obras",
    "assuntos jurídicos": "Ouvidoria Geral",
    "comunicação social": "Ouvidoria Geral",
    "controle governamental": "Ouvidoria Geral",
    "criança, adolescente e idoso": "Ouvidoria Setorial da Assistência Social",
    "cultura e turismo": "Ouvidoria Geral",
    "defesa civil": "Ouvidoria Geral",
    "direitos à pessoa com deficiência": "Ouvidoria Setorial da Assistência Social",
    "direitos e vantagens do servidor": "Ouvidoria Geral",
    "educação": "Ouvidoria Setorial de Educação",
    "empresas e legalizações": "Ouvidoria Setorial da Fazenda",
    "esporte e lazer": "Ouvidoria Geral",
    "fiscalização e tributos": "Ouvidoria Setorial da Fazenda",
    "fiscalização urbana, regularização e registro de imóveis": "Ouvidoria Setorial de Urbanismo",
    "fundec": "Ouvidoria Setorial da FUNDEC",
    "governança": "Ouvidoria Geral",
    "governo municipal e enterro gratuito": "Ouvidoria Geral",
    "habitação": "Ouvidoria Setorial de Urbanismo",
    "inclusão e acessibilidade": "Ouvidoria Geral",
    "meio ambiente": "Ouvidoria Setorial de Meio Ambiente",
    "meio ambiente (poluição sonora, árvores, licenças e fiscalizações ambientais e etc.)": "Ouvidoria Setorial de Meio Ambiente",
    "assédio": "Ouvidoria Geral",
    "obras públicas": "Ouvidoria Setorial de Obras",
    "obras, limpeza urbana e braço de luz": "Ouvidoria Setorial de Obras",
    "proteção animal": "Ouvidoria Geral",
    "saúde": "Ouvidoria Setorial da Saúde",
    "segurança pública": "Ouvidoria Geral de Segurança Pública",
    "segurança, sinalização e multas": "Ouvidoria Geral de Segurança Pública",
    "trabalho, emprego e renda": "Ouvidoria Geral",
    "transportes e serviços públicos": "Ouvidoria Geral",
    "transportes, serviços públicos e trocada de lâmpadas": "Ouvidoria Geral",
    "urbanismo": "Ouvidoria Setorial de Urbanismo",
    "vigilância sanitária": "Ouvidoria Setorial da Saúde",
    "obras": "Ouvidoria Setorial de Obras",
    "segurança": "Ouvidoria Setorial de Segurança Pública",
    "árvores": "Ouvidoria Setorial de Meio Ambiente",
    "controle de pragas": "Ouvidoria Setorial da Saúde",
    "criação irregular de animais": "Ouvidoria Setorial da Saúde",
    "adolescente e idoso": "Ouvidoria Setorial da Assistência Social",
    "criança": "Ouvidoria Setorial da Assistência Social",
    "fiscalização urbana": "Ouvidoria Setorial de Urbanismo",
    "regularização e registro de imóveis": "Ouvidoria Setorial de Urbanismo",
    "limpeza urbana e braço de luz": "Ouvidoria Setorial de Obras",
    "meio ambiente (poluição sonora)": "Ouvidoria Setorial de Meio Ambiente",
    "licenças e fiscalizações ambientais e etc.": "Ouvidoria Setorial de Meio Ambiente",
    "vetores e zoonoses (combate à dengue)": "Ouvidoria Setorial da Saúde",
    "sinalização e multas": "Ouvidoria Setorial de Segurança Pública"
};

// 4. Map of Responsible Entities to Ombudsman
export const RESPONSIBLE_TO_OMBUDSMAN_MAP = {
    "1ª Residência de Obras": "Ouvidoria Setorial de Obras",
    "2ª Residência de Obras A": "Ouvidoria Setorial de Obras",
    "2ª Residência de Obras B": "Ouvidoria Setorial de Obras",
    "3ª Residência de Obras": "Ouvidoria Setorial de Obras",
    "Aitana de Jesus Santos": "Ouvidoria Setorial de Obras",
    "Amanda Fernandes de Oliveira": "Ouvidoria Setorial de Obras",
    "Ana Paula Cassiano de Oliveira": "Ouvidoria Setorial de Obras",
    "Brenda Rhaianny Machado Lima": "Ouvidoria Setorial de Urbanismo",
    "Departamento de Fiscalização (Meio Ambiente)": "Ouvidoria Setorial de Meio Ambiente",
    "GPE": "Ouvidoria Setorial de Obras",
    "Guilherme Gomes": "Ouvidoria Setorial de Obras",
    "Jessica Cristina Soares Trajano da Rocha": "Ouvidoria Setorial de Obras",
    "Ouvidoria Geral (ADM)": "Ouvidoria Geral",
    "Priscila Tavares Salcedo": "Ouvidoria Setorial de Obras",
    "Secretaria Municipal de Obras": "Ouvidoria Setorial de Obras",
    "Secretaria Municipal de Segurança Pública": "Ouvidoria Setorial de Segurança Pública",
    "Secretaria Municipal de Transportes e Serviços Públicos": "Ouvidoria Geral",
    "Superintendência de Limpeza Urbana": "Ouvidoria Setorial de Obras",
    "Thayná Cristina Dias de Souza": "Ouvidoria Setorial de Obras"
};

// 5. Unit Names Specific Map (UAC/UPA/UPH)
export const UNIT_NAME_MAP = {
    "uac - cer iv": "UAC - CER IV",
    "uac - uph pilar": "UAC - UPH Pilar",
    "uac - uph saracuruna": "UAC - UPH Saracuruna",
    "uac - uph xerem": "UAC - UPH Xerém",
    "uac - upa beira mar": "UAC - UPA Beira Mar",
    "uac - hospital do olho": "UAC - Hospital do Olho",
    "uac - adao pereira nunes": "UAC - Adão Pereira Nunes",
    "ouvidoria setorial da assistencia social": "Ouvidoria Setorial da Assistência Social",
    "ouvidoria geral": "Ouvidoria Geral",
    "ouvidoria setorial da saude": "Ouvidoria Setorial da Saúde",
    "cidadao": "Cidadão",
    "cidadão": "Cidadão"
};
